### ISSUE TITLE
error in node_modules/react-transition-group/cjs/index.js:6:45)

### ISSUE THREAD

**Issue by setimod** [shamahoque/mern-skeleton#5]
I am trying to install the application and I get this error:

<h6>mern-mediastream-second-edition/node_modules/react-transition-group/cjs/index.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
[nodemon] `app crashed - waiting for file changes before starting.`
</h6>

I have installed in a docker container the mongo version 4.2.5 and I have created the database mernproject, from Os i installed nodejs version 13.12 I am using manjaro linux may be this is the problem.
This is my configuration file:
const config = {
  env: process.env.NODE_ENV || 'development',
  port: process.env.PORT || 3000,
  jwtSecret: process.env.JWT_SECRET || "YOUR_secret_key",
  mongoUri: 'mongodb://172.17.0.2:27017/mernproject',
  serverUrl: process.env.serverUrl || 'http://localhost:3000'
}

export default config

/

This is the full log error:

<h6>[mongoose] external "mongoose" 42 bytes {main} [built]
    + 94 hidden modules
/mern-mediastream-second-edition/node_modules/react-transition-group/cjs/Transition.js:452
    current: _propTypes.default.instanceOf(Element)
                                           ^

ReferenceError: Element is not defined
    at Object.<anonymous> (/mern-mediastream-second-edition/node_modules/react-transition-group/cjs/Transition.js:452:44)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mern-mediastream-second-edition/node_modules/react-transition-group/cjs/CSSTransition.js:14:42)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mern-mediastream-second-edition/node_modules/react-transition-group/cjs/index.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
[nodemon] app crashed - waiting for file changes before starting...
</h6>

**Comment by shamahoque** [comment]
This seems related to the following issue:
https://github.com/reactjs/react-transition-group/issues/618

Installing the versions as specified in the package.json and yarn.lock from this repository does not throw this error.
