### ISSUE TITLE
Expected type of "path" argument is string but received InternalServerError

### ISSUE THREAD

**Issue by aaditkamat** [shamahoque/mern-skeleton#7]
I have modified the template significantly for a project I'm working on. However, I would like to highlight this error that I get when I run the web application sometimes because I believe it stems from the original code. 

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of InternalServerError
    at validateString (internal/validators.js:121:11)
    at extname (path.js:1229:5)
    at new View (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/view.js:56:14)
    at Function.render (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/response.js:1012:7)
    at eval (webpack:///./server/express.js?:184:7)
    at Layer.handle_error (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:315:13)
    at /Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:315:13)
    at /Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/aadit/WebStormProjects/FWSearch/node_modules/express/lib/router/index.js:275:10)
```

The error occurs pretty arbitrararily and I think it may be due to this block of code:

https://github.com/shamahoque/mern-skeleton/blob/1e28284d20c06ca8ab91b849797d323c76107e68/server/express.js#L50-L58

**Comment by shamahoque** [comment]
This block of code is responsible for server-side rendering the React components and is invoked when the server receives a request at a route that doesn't match any of the routes already defined in the backend. 

This does seem like a backend route related issue, so you can expect the error to only be thrown when you visit an app URL directly from the address bar or make an API request directly to the server (using fetch, axios, ajax, etc). But not due to browsing within the application by visiting frontend routes.

From the error log, it looks like an error specific to express trying to handle a route request where the path provided is an error object rather than a string. I would look into where this might be happening in the code, it might be caused by a third-party lib or middleware function or in the way a request is made to the server.

**Comment by aaditkamat** [comment]
@shamahoque, I had a look at my app and it may have been because I rendered error object as a response for client side errors with `res.send(createError(errorCode))` using the [`http-errors` module](https://yarnpkg.com/package/http-errors), in place of sending a JSON response
https://github.com/shamahoque/mern-skeleton/blob/1e28284d20c06ca8ab91b849797d323c76107e68/server/express.js#L70-L77

I'm closing the issue since I've not gotten that error again since I switched back to the original code
